---

- name: install python-pip
  become: true
  apt:
    name: python-pip
    state: present

- name: install pydf
  pip:
    name: pydf
    state: present
    virtualenv_site_packages: yes

# tasks file for create_user