---

- name: Add the ondrej PHP PPA
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Update the apt cache
  # become: yes
  apt:
    update_cache: yes

- name: Install PHP
  # become: yes
  apt:
    # name={{item}}
    name={{item}} state=latest
  with_items:
      - php
      - php-fpm
      - php-mysql
      - php-xml

- name: Remove apache2
  # become: yes
  apt:
    name: apache2
    state: absent


# tasks file for create_user