---

- name: clone oh-my-zsh
  become: no
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: ~/.oh-my-zsh
    update: no

# tasks file for create_user
- name: change file .zshrc
  become: no
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    force: no

- name: zsh-autosuggestions
  become: no
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
    update: no

- name: replace zshrc
  become: no
  lineinfile:
    path: ~/.zshrc
    # ^ is start of line, $ is end of line
    regexp: '^  git$'
    line: '  git zsh-autosuggestions'
    backrefs: yes

- name: replace color
  become: no
  lineinfile:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    regexp: 'fg=8'
    line: 'fg=blue'
    backrefs: yes
